In [1]:
import numpy as np

In [2]:
import scipy

$$4x  + 3y = 20$$

$$-5x + 9y = 26$$

In [2]:
m_list = [[4, 3], [-5, 9]]

In [3]:
m_list

[[4, 3], [-5, 9]]

In [4]:
A = np.array(m_list)

In [5]:
A

array([[ 4,  3],
       [-5,  9]])

In [6]:
inv_A = np.linalg.inv(A)

In [7]:
inv_A

array([[ 0.17647059, -0.05882353],
       [ 0.09803922,  0.07843137]])

In [8]:
B = np.array([20, 26])

In [9]:
B

array([20, 26])

In [10]:
X = np.linalg.inv(A).dot(B)

In [11]:
X

array([2., 4.])

$$4x + 3y + 2z = 25$$

$$-2x + 2y + 3z = -10$$

$$3x -5y + 2z = -4$$

In [12]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X = np.linalg.inv(A).dot(B)

print(X)

[ 5.  3. -2.]


# `solve()`

$$4x + 3y + 2z = 25$$

$$-2x + 2y + 3z = -10$$

$$3x -5y + 2z = -4$$

In [15]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X2 = np.linalg.solve(A,B)

print(X2)

[ 5.  3. -2.]


In [14]:
from scipy import linalg

In [19]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])

X3 = linalg.solve(A, B)
print(X3)

np.dot(A, X3) == B

[ 5.  3. -2.]


array([ True,  True,  True])

$$8x + 3y - 2z = 9$$

$$-4x + 7y + 5z = 15$$

$$3x + 4y - 12z = 35$$

In [31]:
A = np.array([[8, 3, -2],[-4, 7, 5],[3, 4, -12]])

B = np.array([9, 15, 35])

In [32]:
A

array([[  8,   3,  -2],
       [ -4,   7,   5],
       [  3,   4, -12]])

In [33]:
B

array([ 9, 15, 35])

In [34]:
X = np.linalg.solve(A, B)

In [35]:
np.dot(A, X)

array([ 9., 15., 35.])

In [36]:
X

array([-0.58226371,  3.22870478, -1.98599767])

https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/

https://www.datacamp.com/community/blog/python-scipy-cheat-sheet

https://docs.scipy.org/doc/scipy/reference/linalg.html

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html#scipy.linalg.solve

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv

https://numpy.org/doc/stable/reference/routines.linalg.html

# Quiz attempt 1

In [4]:
A = np.array([[0, -2, 7], [12, 3, 8], [-4, 9, 0], [7, 6, -1]])

In [5]:
A

array([[ 0, -2,  7],
       [12,  3,  8],
       [-4,  9,  0],
       [ 7,  6, -1]])

In [6]:
np.matrix.transpose(A)

array([[ 0, 12, -4,  7],
       [-2,  3,  9,  6],
       [ 7,  8,  0, -1]])

In [7]:
0 + (-27) + (-15) + 0

-42

In [17]:
x = np.array([[1, -4, 15],[9, -6, 13]])

In [18]:
x

array([[ 1, -4, 15],
       [ 9, -6, 13]])

In [19]:
x.shape

(2, 3)

In [20]:
y = np.array([[4, 3],[-3, 0],[5, 1],[0, 7]])

In [21]:
y

array([[ 4,  3],
       [-3,  0],
       [ 5,  1],
       [ 0,  7]])

In [22]:
y.shape

(4, 2)

In [23]:
np.dot(x,y)

ValueError: shapes (2,3) and (4,2) not aligned: 3 (dim 1) != 4 (dim 0)

In [24]:
A = np.array([[0, -2], [4, 7]])
B = np.array([1, 2])
X2 = np.linalg.solve(A,B)

print(X2)

[ 1.375 -0.5  ]


In [25]:
11/8

1.375

In [26]:
A = np.array([[2, -3, 1], [4, 2, -5], [-2, 2, 1]])
B = np.array([2, -1, -5])
X2 = np.linalg.solve(A,B)

print(X2)

[-2.55555556 -3.44444444 -3.22222222]


In [29]:
23/9

2.5555555555555554

In [30]:
13/9

1.4444444444444444

In [31]:
-31/9

-3.4444444444444446

In [32]:
-29/9

-3.2222222222222223

In [33]:
A = np.array([[3, 1], [2, -5]])
B = np.array([2, 1])
X2 = np.linalg.solve(A,B)

print(X2)

[0.64705882 0.05882353]


In [34]:
0.64705882 / 0.05882353

10.999999830000002

In [35]:
A = np.array([[1, -2, 3], [-3, 0, 2], [1, -1, 4]])
B = np.array([5, 2, 6])
X2 = np.linalg.solve(A,B)

print(X2)

[ 0.23529412 -0.35294118  1.35294118]


In [36]:
4/17

0.23529411764705882

In [37]:
A = np.array([[3, 5, -1],[-4, 1, 2],[0, 1, 0]])

In [38]:
np.linalg.inv(A)

array([[  1. ,   0.5,  -5.5],
       [  0. ,   0. ,   1. ],
       [  2. ,   1.5, -11.5]])

In [39]:
A = np.array([[0, 5, 1],[-2, 1, -4],[1, 6, 0]])

In [40]:
A

array([[ 0,  5,  1],
       [-2,  1, -4],
       [ 1,  6,  0]])

In [41]:
np.linalg.inv(A)

array([[-0.72727273, -0.18181818,  0.63636364],
       [ 0.12121212,  0.03030303,  0.06060606],
       [ 0.39393939, -0.15151515, -0.3030303 ]])

In [42]:
 0.12121212/ -0.3030303

-0.4000000000000001

In [44]:
np.array([])

array([], dtype=float64)