https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html

# Inverse of a matrix

\begin{bmatrix}
1 & 3 & 5\\
2 & 5 & 1\\
2 & 3 & 8
\end{bmatrix}

In [2]:
import numpy as np
from scipy import linalg

In [4]:
A = np.array([[1,3,5],
            [2,5,1],
            [2,3,8]])

In [5]:
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [6]:
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [7]:
A.dot(linalg.inv(A))

array([[ 1.00000000e+00, -1.11022302e-16, -5.55111512e-17],
       [ 3.05311332e-16,  1.00000000e+00,  1.87350135e-16],
       [ 2.22044605e-16, -1.11022302e-16,  1.00000000e+00]])

# Solving a linear system

In [10]:
A = np.array([[1, 2], [3, 4]])
print(A)

b = np.array([[5], [6]])
print(b)

[[1 2]
 [3 4]]
[[5]
 [6]]


In [11]:
np.linalg.solve(A,b)

array([[-4. ],
       [ 4.5]])

# Finding the determinant

In [12]:
A = np.array([[1,2,3],
             [4,5,6],
             [10,11,14]])

linalg.det(A)

-5.999999999999995

In [13]:
A = np.array([[1,2],[3,4]])
A


linalg.det(A)

-2.0