## Task: array with values that are spaced linearly in a specified interval

[source:](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [1]:
import numpy as np

In [2]:
np.linspace(1, 2, 3)

array([1. , 1.5, 2. ])

In [4]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [8]:
np.linspace(1.0, 4.0, 10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])