In [1]:
import numpy as np

In [2]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [3]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [4]:
np.linspace(3, 10, 10)

array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])