## task: matrix inverse using numpy

source: Python data analysis (2021, Packt), Page 118

In [1]:
import numpy as np

In [2]:
#create a matrix using numpy

In [3]:
matrix = np.mat([[2,4], [5,7]])

In [4]:
matrix

matrix([[2, 4],
        [5, 7]])

In [5]:
inverse = np.linalg.inv(matrix)

In [6]:
inverse

matrix([[-1.16666667,  0.66666667],
        [ 0.83333333, -0.33333333]])

In [11]:
matrix2 = np.mat([[2, 4, 4],[3, -6, 9],[1, 0, 5]])

In [12]:
matrix2

matrix([[ 2,  4,  4],
        [ 3, -6,  9],
        [ 1,  0,  5]])

In [13]:
matrix2.shape

(3, 3)

In [14]:
inverse2 = np.linalg.inv(matrix2)

In [15]:
inverse2

matrix([[ 0.5       ,  0.33333333, -1.        ],
        [ 0.1       , -0.1       ,  0.1       ],
        [-0.1       , -0.06666667,  0.4       ]])

In [26]:
matrix3 = np.array([2, 4, 4, 3, -6, 9, 1, 0, 5])

In [27]:
matrix3 = matrix3.reshape((3,3))

In [28]:
matrix3

array([[ 2,  4,  4],
       [ 3, -6,  9],
       [ 1,  0,  5]])

In [29]:
matrix3 = np.mat(matrix3)

In [30]:
matrix3

matrix([[ 2,  4,  4],
        [ 3, -6,  9],
        [ 1,  0,  5]])

In [31]:
np.linalg.inv(matrix3)

matrix([[ 0.5       ,  0.33333333, -1.        ],
        [ 0.1       , -0.1       ,  0.1       ],
        [-0.1       , -0.06666667,  0.4       ]])