## Task: finding the rank of a matrix

Source: Python Data Analysis(Packt, 2021), Page 117

In [1]:
import numpy as np

In [2]:
from numpy.linalg import matrix_rank

In [3]:
import random

In [10]:
data = random.sample(range(0, 20), 9)

In [11]:
data

[13, 5, 3, 15, 12, 19, 10, 4, 8]

In [12]:
mat = np.mat(np.array(data).reshape((3,3)))

In [13]:
mat

matrix([[13,  5,  3],
        [15, 12, 19],
        [10,  4,  8]])

In [14]:
matrix_rank(mat)

3

In [16]:
data_more = random.sample(range(100, 220), 9)

In [17]:
data_more

[212, 171, 195, 110, 183, 120, 180, 144, 179]

In [18]:
mat2 = np.mat(np.array(data_more).reshape(3,3))

In [19]:
mat2

matrix([[212, 171, 195],
        [110, 183, 120],
        [180, 144, 179]])

In [20]:
matrix_rank(mat2)

3

In [22]:
testing = random.sample(range(1, 1000), 9)

mat3 = np.mat(np.array(testing).reshape(3,3))

In [23]:
mat3

matrix([[133, 981, 942],
        [610, 645, 750],
        [518, 679, 893]])

In [24]:
matrix_rank(mat3)

3

In [25]:
np.linalg.inv(mat3)

matrix([[-0.00096787,  0.00342876, -0.00185872],
        [ 0.00226583,  0.00535438, -0.00688711],
        [-0.00116141, -0.00606016,  0.00743468]])